language: python
python:
  - 3.9

branches:
  only:
    - production
    - staging

services:
  - docker

stages:
  - Test
  # - Github Packages Deploy

jobs:
  include:
    - stage: Test
      before_script:
        - cp ./bin/env/.env.sample ./bin/env/.env.local
        - pip install coveralls
      script:
        - make tests.ci
        - coveralls

    - stage: Github Packages Deploy
      if: (NOT type IN (pull_request)) AND (branch = production)
      env: TAG=$(date +%d%m%Y%H%M%S)
      script: make push.prod
