# Generated by Django 4.0.3 on 2022-04-18 08:38

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import localized_fields.fields.char_field
import localized_fields.fields.text_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shelters', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], db_index=True, max_length=1)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('description', localized_fields.fields.text_field.LocalizedTextField(blank=True, null=True, required=[])),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', localized_fields.fields.char_field.LocalizedCharField(blank=True, db_index=True, null=True, required=[], uniqueness=['en', 'es'])),
                ('weight', django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True)),
                ('life_span', django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True)),
                ('origins', models.ManyToManyField(to='places.country')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', localized_fields.fields.char_field.LocalizedCharField(blank=True, db_index=True, null=True, required=[], uniqueness=['en', 'es'])),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='animals.animal')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('animals.animal',),
        ),
        migrations.CreateModel(
            name='CatBreed',
            fields=[
                ('breed_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='animals.breed')),
                ('dog_friendly', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('child_friendly', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('animals.breed',),
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('animal_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='animals.animal')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('animals.animal',),
        ),
        migrations.CreateModel(
            name='DogBreed',
            fields=[
                ('breed_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='animals.breed')),
                ('height', django.contrib.postgres.fields.ranges.IntegerRangeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('animals.breed',),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='animals.animal')),
            ],
        ),
        migrations.AddField(
            model_name='breed',
            name='tags',
            field=models.ManyToManyField(related_name='breeds', to='animals.tag'),
        ),
        migrations.AddField(
            model_name='animal',
            name='breeds',
            field=models.ManyToManyField(related_name='animals', to='animals.breed'),
        ),
        migrations.AddField(
            model_name='animal',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='animal',
            name='shelter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shelters.shelter'),
        ),
    ]
