# Generated by Django 4.0.3 on 2022-04-18 08:38

from django.db import migrations, models
import django.db.models.deletion
import localized_fields.fields.char_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', localized_fields.fields.char_field.LocalizedCharField(blank=True, db_index=True, null=True, required=[])),
                ('alpha2', models.CharField(db_index=True, max_length=2, unique=True)),
                ('alpha3', models.CharField(db_index=True, max_length=3, unique=True)),
                ('numeric', models.CharField(max_length=3, unique=True)),
                ('phone_prefix', models.CharField(max_length=32)),
                ('continent', models.CharField(max_length=2)),
                ('capital', models.CharField(max_length=255)),
                ('locale', models.CharField(max_length=8)),
            ],
            options={
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='ISO 4217', max_length=3, unique=True)),
                ('numeric', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('symbol', models.CharField(max_length=4)),
            ],
            options={
                'verbose_name_plural': 'currencies',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(db_index=True)),
                ('name', localized_fields.fields.char_field.LocalizedCharField(blank=True, db_index=True, null=True, required=[])),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.country')),
            ],
            options={
                'unique_together': {('country', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=2)),
                ('name', localized_fields.fields.char_field.LocalizedCharField(blank=True, db_index=True, null=True, required=[])),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.region')),
            ],
            options={
                'unique_together': {('region', 'code')},
            },
        ),
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.currency'),
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(db_index=True, null=True)),
                ('name', localized_fields.fields.char_field.LocalizedCharField(blank=True, db_index=True, null=True, required=[])),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.province')),
            ],
            options={
                'verbose_name_plural': 'cities',
                'unique_together': {('province', 'code')},
            },
        ),
    ]
